FROM gcc:12

WORKDIR /usr/src/app

COPY src/cpp_server/ ./src/
COPY data/ ./data/

WORKDIR /usr/src/app

# RUN g++ -std=c++17 -pthread -o MailProject main.cpp TCP_Server.cpp BloomFilter.cpp bloom_setup.cpp UrlStorage.cpp UrlListUtils.cpp URLChecker.cpp InfiniteCommandLoop.cpp

RUN g++ -std=c++17 -pthread -o MailProject \
  src/main.cpp \
  src/TCP_Server.cpp \
  src/BloomFilter.cpp \
  src/bloom_setup.cpp \
  src/UrlStorage.cpp \
  src/UrlListUtils.cpp \
  src/URLChecker.cpp \
  src/InfiniteCommandLoop.cpp


EXPOSE 5555
CMD ["./MailProject", "0.0.0.0", "5555", "256", "8", "8"]
